### ISSUE TITLE
TODO'S

### ISSUE THREAD

**Issue by netosouzasoares** [netosouzasoares/eng-gruposbf-backend-python#24]
- [ ] after push image docker to dockerhub, we need to implement CD to kubernetes/ec2 e etc...
- [ ] configure newrelic/datadog/ to private account
- [ ] configure sentry to private account
